package com.unitglo.foodscience;

import java.util.ArrayList;

public class StaticLists {
	public static ArrayList<BaseFruits> baseFruitsaArrayList = new ArrayList<BaseFruits>();
	public static ArrayList<BaseFruits> baseVegetablesArrayList = new ArrayList<BaseFruits>();
	public static ArrayList<BaseFruits> baseSpicesArrayList = new ArrayList<BaseFruits>();

	public static void FillFruatsInfo() {
		String[][] NutritionFacts1 = {
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" } };

		String[][] NutritionFacts2 = {
				{ "52", "0.2 g", "0 mg", "1 mg", "107 mg", "14 g", "0.3 g" },
				{ "48", "0.4 g", "0 mg", "1 mg", "259 mg", "11 g", "1.3 g" },
				{ "160", "15 g", "0 mg", "7 mg", "485 mg", "9 g", "2 g" },
				{ "89", "0.3 g", "0 mg", "1 mg", "358 mg", "23 g", "1.1 g" },
				{ "50", "0.3 g", "0 mg", "3 mg", "173 mg", "12 g", "1 g" },
				{ "83", "1.1 g", "0 mg", "12 mg", "193 mg", "20 g", "0.4 g" },
				{ "47", "0.2 g", " - ", "1 mg", "177 mg", "12 g", "0.8 g" },
				{ "354", "33 g", "0 mg", "20 mg", "356 mg", "15 g", "3.3 g" },
				{ "94", "0.3 g", "0 mg", "9 mg", "247 mg", "24 g", "2.1 g" },
				{ "282", "0.4 g", " - ", "2 mg", "656 mg", "75 g", "2.4 g" },
				{ "73", "0.5 g", "0 mg", "6 mg", "280 mg", "18 g", "0.7 g" },
				{ "74", "0.4 g", "0 mg", "1 mg", "232 mg", "19 g", "0.8 g" },
				{ "67", "0.4 g", "0 mg", "2 mg", "191 mg", "17 g", "0.6 g" },
				{ "68", "1 g", "0 mg", "2 mg", "417 mg", "14 g", "2.6 g" },

				{ "29", "0.3 g", "0 mg", "2 mg", "138 mg", "9 g", "1.1 g" },

				{ "61", "0.5 g", "0 mg", "3 mg", "312 mg", "15 g", "1.1 g" },
				{ "60", "0.4 g", "0 mg", "1 mg", "168 mg", "15 g", "0.8 g" },
				{ "34", "0.2 g", "0 mg", "16 mg", "267 mg", "8 g", "0.8 g" },
				{ "39", "0.2 g", "0 mg", "16 mg", "190 mg", "10 g", "0.9 g" },
				{ "47", "0.1 g", "0 mg", "0 mg", "181 mg", "12 g", "0.9 g" },
				{ "57", "0.1 g", "0 mg", "1 mg", "116 mg", "15 g", "0.4 g" },
				{ "50", "0.1 g", "0 mg", "1 mg", "109 mg", "13 g", "0.5 g" },

				{ "43", "0.3 g", "0 mg", "8 mg", "182 mg", "11 g", "0.5 g" },

				{ "45", "0.3 g", "0 mg", "0 mg", " - ", "11 g", "1 g" },
				{ "46", "0.3 g", "0 mg", "0 mg", "157 mg", "11 g", "0.7 g" },
				{ "83", "1.2 g", "0 mg", "3 mg", "236 mg", "19 g", "1.7 g" },
				{ "60", "0 g", "0 mg", "14 mg", "-", "16 g", "1 g" },

				{ "30", "0.2 g", "0 mg", "1 mg", "112 mg", "8 g", "0.6 g" } };
		String[][] vari = {
				{ "Braeburn", "Cortland", "Fuji", "Gala", "Ginger Gold",
						"Golden Delicious", "Red Delicious", "Granny Smith",
						"Honeycrisp", "Jonathan", "Jonagold", "McIntosh",
						"Pacific Rose", "Paula Red", "Wealthy" },
				{ "Apium", "August Glo", "Autumn Royal", "Blenheim",
						"Chinese (Mormon)", "Earligold", "Floragold",
						"Garden Annie", "Gold Kist", "Goldcot", "Golden Amber",
						"Harcot", "Harglow", "Hargrand", "Harogem", "Katy",
						"King", "Manchurian apricot", "Montrose", "Moongold",
						"Moorpark", "Newcastle", "Perfection (Goldbeck)",
						"Plum Parfait", "Puget Gold", "Riland", "Rival",
						"Royal Rosa", "Royalty", "Stark Tilton", "Sungold",
						"Sun-Glow", "Tilton", "Tomcot", "Wenatchee Moorpark" },
				{ "Shepard", "Choquette", "Tonnage", "Daily 11", "Macarthur",
						"Hall", "Mexicola Grande", "Anaheim", "Hass" },
				{ "Apple Bananas", "Cavendish Bananas", "Lady Finger Bananas",
						"Pisang King", "Williams Bananas", "Cooking Bananas" },
				{ "Abundance  cherry", "Adriana  cherry", "Alba Heart  cherry",
						"Amber Heart  cherry", "Ambrunes  cherry",
						"Angela  cherry", "Annabella  cherry",
						"Arcina  cherry", "Attika  cherry",
						"August Heart  cherry" },
				{ "Brown Sugar", "Prolific", "Russel", "Tikal" },
				{ "Clemenules", "Nules", "Nadorcott" },
				{ "West - cost tall", "Laccadiv Micro", "Andaman ordinary",
						"Fiji", "Kappadam", "San Ramon", "Philippines",
						"Spicate", "Pratap" },
				{ "Pinks Mammoth", "African Pride" },

				{ "Ammari", "Angou", "Arichti", "Bejjou", "Bisr Helou",
						"Dayri", "Gounda", "Gousbi", "Branch of Hamraya dates",
						"Hissa", "Kenta", "Kentichi", "Lagou", "Sukkary",
						"Trounja" },
				{ "Adams No. 2", "York", "Johns", "Scotia" },
				{ "Commom Fig", "Caprifig", "Smyrna Fig", "San Pedro Fig",
						"Adriatic Fig", "Black Mission Fig",
						"Brown Turkey Fig", "Calimyrna Fig", "Sierra Fig",
						"King Fig", "Kadota Fig", "Strangler Fig" },
				{ "Auxerrois", "Barbera", "Cabernet Franc",
						"Cabernet Sauvignon", "Chardonnay", "Chenin Blanc",
						"Cinsaut", "Colombard", "Cortese", "Ehrenfelser",
						"Gamay", "Gewurztraminer", "Grande Vidure", "Grenache",
						"Kerner", "Lemberger", "Maréchal Foch", "Merlot",
						"Muller", "Muscadet", "Muscadine", "Muscat",
						"Muskat Krymskii", "Nebbiolo", "Optima", "Ortega",
						"Petite Sirah", "Pinot Blanc", "Pinot Gris",
						"Pinot grigio", "Pinot Noir", "Pinotage", "Riesling",
						"Sauvignon Blanc", "Scheurebe", "Semillon", "Seyval",
						"Sylvaner", "Syrah/Shiraz", "Siegerrebe",
						"Tempranillo", "Viognier", "Vidal Blanc" },
				{ "Strawberry Guava", "Pineapple Guava", "Beaumont",
						"China White", "Mexican Cream", "Red Malaysian",
						"South African", "White Indian" },
				{ "Sour Lemon", "Eureka Lemon", "Lisbon Lemon", "Pink Lemons",
						"Rough Lemon", "Sweet Lemons", "Sanbokan Lemon",
						"Meyer Lemons" },

				{ "Green Kiwi", "Golden Kiwi", "Red Kiwis", "Kiwi Berry" },
				{ "Alphonso", "Banganapalli", "Saroli/Bombay Green", "Chaunsa",
						"Dashehari", "Fazli", "Gulab Khas", "Himsagar",
						"Kesar", "Kishenbhog", "Langra", "Mankurad", "Neelam",
						"Pairi", "Totapuri", "Mallika" },
				{ "Navel Oranges", "Valencia Oranges", "Moro (Blood) Oranges",
						"Cara Cara Oranges", "Hamlin Oranges",
						"The Cleopatra Orange", "Mandarin Orange",
						"Tangerine Orange" },
				{ "Anjou Pears", "Asian Pears", "Bartlett Pears", "Bosc Pears",
						"Comice Pears", "Forelle Pears", "Seckel Pears" },
				{ "Smooth Cayenne", "Abacaxi", "Queen", "Red Spanish" },
				{ "Cooke's Jumbo Quince", "Jumbo Quince", "Orange Quince",
						"Pineapple Quince", "Smyrna Quince" },
				{ "Oblate", "Globose", "Globose Conic", "Conic", "Long Conic",
						"Necked", "Long Wedge", "Short Wedge" },

				{ "Kapoho Papaya", "Sunrise and Sunset Papayas", "Waimanalo",
						"Mexican Papayas", "Babaco Papayas", "Kamiah Papaya" },

				{ "Redhaven", "Glohaven", "Red Globe", "Canadian Harmony",
						"Early Elberta", "Elberta", "J.H. Hale", "Veteran",
						"Reliance", "Harken", "Polly", "Ranger" },
				{ "Ruby royal plum", "Black diamond plum", "Pluot",
						"Black amber plum", "Amber jewel", "Blood plum",
						"Angelina" },
				{ "Angel Red Pomegranate", "Granada Pomegranate",
						"State Fair Pomegranate", "Eight Ball Pomegranate",
						"Nana Pomegranate", "Babylonian White Pomegranate",
						"Dwarf Pomegranate", "Goliath Pomegranate",
						"Grenada Pomegranate", "Plantation Sweet Pomegranate",
						"Russian Pomegranate", "Scaly Bark Tree Form" },
				{ "Jambolana" },

				{ "Sugar Baby", "Sangria", "Golden Midget", "Starlight",
						"Jubilee", "Starbrite", "Extazy", "Stars ‘n’ Stripes",
						"Mickylee", "Yellow Baby", "Yellow Doll",
						"Little Baby Flower", "Crimson Sweet", "Pixie",
						"Summer Flavor", "Moon and Stars", "Sweet Favorite",
						"Cream of Saskatchewan" } };
		String[][] Health_Benefits = {
				{ "Weight Loss", "Brain Health ", "Cancer",
						"Metabolic Syndrome", "Antioxidants", "Lung Health",
						"Heart Health", "Immunity", "Gut Health" },
				{ "Is good for your eyes", "Rich source of antioxidants",
						"High Fiber Content", "Healthy for your heart",
						"Potassium for a healthy you", "Non-heme Iron",
						"Cancer", "Skin benefits", "Helps you lose weight",
						"Strengthens your bones", "Electrolyte content" },
				{ "Healthy for the heart", "Great for vision",
						"Osteoporosis prevention", "Cancer fighter",
						"Healthy babies", "Lowered risk of depression",
						"Improved digestion", "Natural detoxification",
						"Protection from chronic disease" },
				{ "Banana Skin for Treating Skin", "Hair Problems",
						"Acts as protective scavengers", "Potassium",
						"Antacid effect", "Normal Heart Function",
						"Overcoming Depression", "Diabetes",
						"Benefits for Weight Loss", "Boosts Energy",
						"Calories", "Enhances Digestive Ability",
						"Natural Ulcer Remedy" },
				{ "Protection from Diabetes", "Helps You Sleep Better",
						"Decreases Belly Fat", "Helps Ward of Alzheimer’s",
						"Reduces Risk of Stroke", "Slows the Aging of Skin",
						"Lowers Risk of Gout Attacks", "Reduces Muscle Pain",
						"Good for the Heart",
						"Helps with osteoarthritis relief",
						"Helps to Prevent Colon Cancer" },
				{ "Increase Eye Quality", "Healthy and Strengthen Bones",
						"High Vitamin B Content", "More Healthy Skin",
						"Prevent various kinds of Cancers",
						"Boost Immune System", "Constipation",
						"Beneficial During Pregnancy", "Fatigue and Stress",
						"Inflammation", "Energy Booster", "Diarrhea",
						"Cold and Cough", "Kidney Stones", "Mental Health",
						"Tooth Cavities" },
				{ "Healthy skin", "Good for brain", "Immune booster",
						"Strong bones and muscles", "Digestive health",
						"Cardiovascular health", "Electrolyte balance",
						"Cancer" },
				{ "Helps Prevent Obesity ", "& over weight",
						"Improves Heart Health",
						"Helps to prevent from the diabetes",
						"Improves Digestion", "Quick Energy Boost",
						"Keeps blood vessels flexible and elastic",
						"Makes bones stronger ",
						"& prevents from osteoporosis",
						"Helps to prevent anemia",
						"Relaxes muscles and nerves",
						"Decreases the risk of arthritis",
						"Lowers high blood pressure",
						"Maintains healthy immune system",
						"Promotes the health of prostate gland", "Hair Care",
						"Skin Care", "Healing and Infections" },
				{ "Helps To Gain Weight", "For A Better Immune System",
						"Replenish Your Energy Levels",
						"Natural Anti-cancerous Properties",
						"For Better Brain Health",
						"For A Strong Dental System",
						"Keep Anemia Away With Custard Apple",
						"For A Better Vision", "Lower The Risk Of Arthritis",
						"For Better Cardiovascular Health",
						"Thwarts Off Diabetes",
						"For A Stronger Digestive System",
						"Good For Fetal Skin And Hair",
						"Prevents Premature Labor",
						"Good For Fetal Brain Development",
						"Excellent Source Of Iron", "Keeps Infections At Bay",
						"Natural Antidote For Morning Sickness" },
				{ "Richer in Fiber", "Lower in Sugar",
						"Higher Source of Minerals", "Lower in Calories",
						"Removing Harmful Estrogens" },
				{ "Bosts immune system", "Relives flu symptoms",
						"Alleviates sinus pain", "Wegiht loss",
						"Improve vision", "Reducing cholestrol",
						"Prevents from flu", "Reduces fever",
						"Improves constipation" },
				{ "Prevention of constipation", "Weight loss",
						"Lower cholesterol", "Prevention of colon cancer",
						"Good for diabetic patients",
						"Prevention of hypertension", "Bronchitis",
						"Venereal Diseases", "Sexual Dysfunction",
						"Strengthens Bones", "Urinary calcium loss" },
				{ "Asthma", "Bone Health", "Heart diseases", "Migraine",
						"Constipation", "Indigestion", "Fatigue", "Diabetes",
						"Dental Care", "Kidney disorders", "Blood cholesterol",
						"Antibacterial activity", "Breast cancer",
						"Alzheimer’s disease", "Macular degeneration",
						"Immune System" },
				{ "Lowers cancer risk", "Lowers risk of diabetes",
						"Promotes good eyesight", "Helps promote fertility",
						"Regulate blood pressure levels",
						"Promotes healthy thyroid gland",
						"Relaxes nerves and muscles", "Keeps brain healthy",
						"Maintain healthy skin", "High Cholesterol",
						"Helps in Weight Loss" },
				{ "Helps to cure Indigestion ", "& Constipation",
						"Reduces Fever", "Dental Care", "Hair and Skin Care",
						"Lightens the Scars from Burns",
						"Prevents from Rheumatism & Gout",
						"Helps to lose Weight", "Treats Cholera", "Cures Corn",
						"Flu, Common Colds, Sore Throat ", "& Other Disease",
						"High Blood Pressure ", "& Heart Disease",
						"Prevents from the Cancer", "Cure osteoarthritis",
						"Kidney & Liver & Pancreas", "Immunity" },
				{ "Beautiful Skin", "Better Sleep", "Heart Health",
						"Lowering Blood Pressure", "Constipation Prevention",
						"Prevents Asthma" },
				{ "Prevents Cancer", "Lowers Cholesterol", "Clears the Skin",
						"Eye Health", "Alkalizes the Whole Body",
						"Helps in Diabetes", "Improved Sex",
						"Improves Digestion", "Remedy for Heat Stroke",
						"Boosts Immune system" },
				{ "Treats Arteriosclerosis", "Cancer prevention",
						"Lowers Cholesterol level", "Cure Constipation",
						"Repairs Damaged sperm",
						"Prevents from the Heart disease",
						"Controls High blood pressure", "Increases Immunity",
						"Prevents Kidney stones", "Protects Skin",
						"Heals Stomach ulcer",
						"Protects against Viral infections",
						"Antioxidant Properties", "Prevents from diabetes",
						"Prevents rheumatoid arthritis",
						"Essential for the healthy bones" },
				{ "Immune System Booster", "Prevents Osteoporosis",
						"Increases Energy Levels", "Cure Cancer",
						"For Healthy Pregnancy", "Hypo Allergenic fruit",
						"Good for Weaning", "Lowers blood pressure",
						"Reduces Cholesterol level", "For Healthy Colon",
						"Relief Constipation", "Inflammation",
						"Shortness of breath", "Throat problem",
						"Digestion and weight control",
						"Good functioning of heart", "Diabetics",
						"Treat Thyroid problems" },
				{ "Asthma prevention", "Blood pressure", "Cancer", "Diabetes",
						"Digestion", "Fertility", "Healing and Inflammation",
						"Heart health", "Skin" },
				{ "Good for weight loss", "Antibacterial",
						"Good for digestion", "Cancer fighting",
						"Good for the heart", "Good for the blood",
						"Good for the immune system", "High antioxidant" },
				{ "Helps burn stored fat", "Boost short term memory",
						"Low in Calories – High in Fiber", "Ease Inflammation",
						"Lower cardiovascular disease", "Promote bone health",
						"Prevent oesophageal cancer", "Anti-aging properties",
						"Good for weight loss", "Promote eye health" },

				{ "Skin Care", "& Macular Degeneration", "Cures Heart Disease",
						"Improve Digestion", "Cancer Prevention",
						"Provides Vitamins and Minerals", "Relieve Nausea",
						"Prevent Constipation", "Lung Protection",
						"Have Anti-inflammatory properties",
						"Works as an Antiseptic", "Helps to lose weight",
						"Nourishes the endocrine system" },
				{ "Cancer", "Skin", "Diabetes", "Heart health" },

				{ "Lowering Cholesterol", "Prevents Cancer",
						"Lower GI (Glycemic Index)",
						"Protects against Oxygen Radical",
						"Helps to Absorb Iron",
						"Keeps Digestive System on Track", "Reduces Aging",
						"Good for Brain Health", "Good for Nourishment",
						"Eliminates Stress", "Eliminates Fatigue",
						"Boost bone health", "Beneficial in the pregnancy",
						"Prevents from the Constipation" },
				{ "Fight Cancer", "Fight Inflammation", "Keep teeth clean",
						"Regulate cholesterol", "Help prevent arthritis",
						"Great source of fiber", "Protect the skin",
						"Fights Breast Cancer", "Lung Cancer Prevention",
						"Keeps PSA Levels Stable",
						"Alzheimer’s Disease Prevention",
						"Used to treat malaria", "Natural blood thinners",
						"Prevention of atherosclerosis",
						"Act like an oxygen mask", "Arthritis prevention",
						"Fight erectile dysfunction",
						"Disease-Fighting Antioxidants",
						"Cardiovascular Health", "Helps Fight Free Radicals",
						"Benefits for Blood Pressure", "Digestive Health",
						"Helps Prevent and Treat Acne", "Prevents Skin Aging",
						"Repairs Skin Cuts and Scrapes", "Dental Protection",
						"Stress Reduction", "Weight and Fat Reduction",
						"Anti-inflammatory properties" },
				{ "Cholesterol Reduction", "Insecticide", "Antibacterial",
						"Blood Sugar Management", "Stomach Aid",
						"Liver Protection", "Anti-Cancer Action", "Diabetes",
						"Polyuria", "Piles", "Liver Disorders",
						"Diarrhea and Dysentery", "Sore Throat" },
				{ "Heart health", "Anti-inflammatory properties", "Hydration",
						"Digestion", "Muscle soreness", "Cancer prevention" } };

		String[] title = { "Nutrition Facts", "Varieties", " Health Benefits" };
		for (int i = 0; i < Fruits.images.length; i++) {
			StaticLists.baseFruitsaArrayList.add(new BaseFruits(
					Fruits.images[i], title, NutritionFacts1[i],
					NutritionFacts2[i], vari[i], Health_Benefits[i]));
		}
	}

	public static void FillVegetablesInfo() {
		String[][] NutritionFacts1 = {
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" },
				{ "Calories", "Total Fat", "Cholesterol", "Sodium",
						"Potassium", "Total Carbohydrate  ", "Protein" } };

		String[][] NutritionFacts2 = {
				{ "47", "0.2 g", "0 mg", "94 mg", "370 mg", "11 g", "3.3 g" },
				{ "25", "0.7 g", "0 mg", "27 mg", "369 mg", "3.6 g", "2.6 g" },
				{ "20", "0.1 g", "0 mg", "2 mg", "202 mg", "3.9 g", "2.2 g" },
				{ "22", "0.6 g", "0 mg", "4 mg", "295 mg", "2.6 g", "3.2 g" },
				{ "341", "1.4 g", "0 mg", "5 mg", "1,483 mg", "62 g", "22 g" },
				{ "43", "0.2 g", "0 mg", "78 mg", "325 mg", "10 g", "1.6 g" },
				{ "13", "0.2 g", "0 mg", "65 mg", "252 mg", "2.2 g", "1.5 g" },
				{ "34", "0.4 g", "0 mg", "33 mg", "316 mg", "7 g", "2.8 g" },
				{ "22", "0.5 g", "0 mg", "33 mg", "196 mg", "2.8 g", "3.2 g" },
				{ "25", "0.1 g", "0 mg", "18 mg", "170 mg", "6 g", "1.3 g" },
				{ "41", "0.2 g", "0 mg", "69 mg", "320 mg", "10 g", "0.9 g" },
				{ "25", " 0.1 g", "0 mg", "30 mg", "303 mg", "5.3 g", "1.98 g" },
				{ "16", "0.2 g", "0 mg", "80 mg", "260 mg", "3 g", "0.7 g" },
				{ "40", "0.2 g", "0 mg", "7 mg", "340 mg", "9 g", "2 g" },
				{ "30", "0.7 g", "0 mg", "3 mg", "296 mg", "4.4 g", "3.3 g" },
				{ "32", "0.6 g", "0 mg", "17 mg", "213 mg", "5 g", "3 g" },
				{ "365", "4.7 g", "0 mg", "35 mg", "287 mg", "74 g", "9 g" },
				{ "16", "0.1 g", "0 mg", "2 mg", "147 mg", "3.6 g", "0.6 g" },
				{ "305", "15 g", "0 mg", "20 mg", "1,186 mg", "55 g", "16 g" },
				{ "25", "0.2 g", "0 mg", "2 mg", "229 mg", "6 g", "1 g" },
				{ "81", "0.4 g", "0 mg", "5 mg", "244 mg", "14 g", "5 g" },
				{ "17", "0.2 g", "0 mg", "22 mg", "314 mg", "3.4 g", "1.2 g" },
				{ "22", "0.7 g", "0 mg", "4 mg", "390 mg", "3.2 g", "2 g" },
				{ "149", "0.5 g", "0 mg", "17 mg", "401 mg", "33 g", "6 g" },
				{ "49", "0.9 g", "0 mg", "38 mg", "491 mg", "9 g", "4.3 g" },
				{ "27", "0.1 g", "0 mg", "20 mg", "350 mg", "6 g", "1.7 g" },
				{ "61", "0.3 g", "0 mg", "20 mg", "180 mg", "14 g", "1.5 g" },
				{ "15", "0.2 g", "0 mg", "28 mg", "194 mg", "2.9 g", "1.4 g" },
				{ "33", "0.2 g", "0 mg", "7 mg", "299 mg", "7 g", "1.9 gF" },
				{ "40", "0.1 g", "0 mg", "4 mg", "146 mg", "9 g", "1.1 g" },
				{ "75", "0.3 g", "0 mg", "10 mg", "375 mg", "18 g", "1.2 g" },
				{ "20", "0.2 g", "0 mg", "3 mg", "175 mg", "4.6 g", "0.9 g" },
				{ "77", "0.1 g", "0 mg", "6 mg", "421 mg", "17 g", "2 g" },
				{ "26", "0.1 g", "0 mg", "1 mg", "340 mg", "6 g", "1 g" },
				{ "23", "0.2 g", "0 mg", "22 mg", "302 mg", "4.5 g", "1.4 g" },
				{ "16", "0.1 g", "0 mg", "39 mg", "233 mg", "3.4 g", "0.7 g" },
				{ "21", "0.2 g", "0 mg", "4 mg", "288 mg", "4.5 g", "0.9 g" },
				{ "38", "0.2 g", "0 mg", "12 mg", "305 mg", "9 g", "1.1 g" },
				{ "42", "0.2 g", "0 mg", "4 mg", "200 mg", "8 g", "2.8 g" },
				{ "23", "0.4 g", "0 mg", "79 mg", "558 mg", "3.6 g", "2.9 g" },
				{ "45", "0.1 g", "0 mg", "4 mg", "352 mg", "12 g", "1 g" },
				{ "86", "0 g", "0 mg", "55 mg", "337 mg", "20 g", "1.6 g" },
				{ "18", "0.2 g", "0 mg", "5 mg", "237 mg", "3.9 g", "0.9 g" },
				{ "28", "0.1 g", "0 mg", "67 mg", "191 mg", "6 g", "0.9 g" },
				{ "311", "7 g", "0 mg", "18 mg", "1,119 mg", "68 g", "11 g" },
				{ "23", "0.5 g", "0 mg", "46 mg", "521 mg", "3.7 g", "2.1 g" },
				{ "80", "0.8 g", "0 mg", "13 mg", "415 mg", "18 g", "1.8 g" },
				{ "247", "1.2 g", "0 mg", "10 mg", "431 mg", "81 g", "4 g" },
				{ "239", "0.6 g", "0 mg", "28 mg", "628 mg", "62 g", "2.8 g" },
				{ "70", "0.9 g", "0 mg", "31 mg", "569 mg", "15 g", "3.8 g" },
				{ "310", "6 g", "0 mg", "148 mg", "1,724 mg", "65 g", "11 g" } };
		String[][] vari = {
				{ "Baby Artichoke", "Globe Artichoke", "Long Stem Artichoke",
						"Purple Artichoke", "Omaha artichoke",
						"Petite mercury artichoke", "Oblong siena artichoke",
						"Purple baby anzio artichoke", "Big heart artichoke",
						"Classic green globe artichoke", "King artichoke",
						"Fiesole artichoke" },
				{ "Cultivated", "Rocket (Roquette)", "Astros" },
				{ "Purple Asparagus", "White Asparagus", "Green Asparagus",
						"Jersey King Asparagus", "Mary Washington Asparagus",
						"Jersey Knight Asparagus Hybrid",
						"Jersey Giant Asparagus", "Purple Passion Asparagus" },
				{ "Christmas Basil", "Cinnamon Basil", "Dark Opal Basil",
						"Holy Basil", "Lemon Basil", "Lime Basil",
						"Spicy Bush Basil", "Purple Ruffles Basil",
						"Round midnight Basil", "Sweet Thai Basil",
						"Sweet Basil", "Greek Basil", "Spicy Saber",
						"Genovese basil", "Cardinal Basil",
						"Green Ruffles (Ocimum basilicum)", "Boxwood basil",
						"Summerlong Basil", "Amethyst Basil", "Ararat Basil",
						"Aroma Basil", "Aussie Purple Basil", "Compatto Basil",
						"Yevani Greek Mini Basil", "Fino Verde Basil",
						"Green Bouquet Basil", "Italian Large Leaf Basil",
						"Lettuce Leaf Basil", "Mini Purple Basil",
						"Red Rubin Basil", "Ruffled Basil",
						"Spicy Globe Basil", "Thai Magic Basil",
						"Thai Siam Queen Basil", "Pesto Perpetuo",
						"Sweet Green Basil", "African Blue Lemon Basil",
						"Albahaca Abundante Basil", "Anise Basil",
						"Aristotle Basil", "Aromatto Basil",
						"Aussie Sweet Basil", "Basilico Basil",
						"Bergamont Basil", "Blue Spice Basil", "Bush Basil",
						"Caesar Basil", "Camphor Basil",
						"Cinnamon Compact Basil", "Clove Basil", "Cuban Basil",
						"Dolce Vita Blend Basil", "Dwarf Greek Basil",
						"East Indian Basil", "Fineleaf Dwarf Basil",
						"Finissimo Basil", "Zulu Basil", "Gecofure Basil",
						"Genovese Red Freddy Basil", "Goddess Basil",
						"Grandi Foglie Valentino", "Green Ruffles Basil",
						"Holy Red-Green Basil", "Italian Cameo Basil",
						"Italiano Classico Basil", "Jacob Kline Basil",
						"Key Lime Basil", "Lemon Lime Basil Blend",
						"Licorice Basil", "Limelight Basil",
						"Magic Blue Basil", "Magic Michael Basil",
						"Magic Mountain Basil", "Magical Michael Basil",
						"Mammoth Basil", "Marseillais Dwarf Basil",
						"Medinette Basil", "Mediterranean Medley Basil",
						"Mexican Basil", "Mexican Cinnamon Spice Basil",
						"Minette Basil", "Minimum Basil", "Mrs. Burns Basil",
						"Napolitano Basil", "New Guinea Basil", "Nufar Basil",
						"Osmin Purple Basil", "Persian Anise Basil",
						"Pesto Perpetuo Basil", "Piccolino Basil",
						"Pinetree Basil", "Pistou Basil", "Plenty Basil",
						"Profuma di Genova Basil", "Purple Basil",
						"Purple Dark Opal Basil", "Purple Delight Basil",
						"Purple Petra Basil", "Queen of Sheba Basil",
						"Queenette Basil", "Red Holy Basil", "Red Osmin Basil",
						"Sacred Thai Basil", "Serata Basil",
						"Siam Queen Thai Basil", "Spicy Saber Basil",
						"Sumatran Basil", "Super Sweet Chen Basil",
						"Superbo Basil", "Sweet Broadleaf Basil",
						"Sweet Dani Basil", "Sweet Genovese Basil",
						"Thai Lemon Basil", "Veseys Blend Basil",
						"Vietnamese Hun Que Basil", "Violetta Aromatico Basil",
						"Wild Purple Basil", "Window Box Basil" },
				{ "Adzuki", "Baby Lima", "Black Bean", "Blackeye", "Cranberry",
						"Dark Red Kidney", "Garbanzo", "Great Northen",
						"Large Lima", "Light Red Kidney", "Navy", "Pink",
						"Pinto", "Small Red" },
				{ "Baby Candy Cane Beet", "Blankoma Beet", "Bull’s Blood Beet",
						"Chiogga Beet", "Golden Beet", "Red Beets",
						"Baby Beets", "White Beets", "Yellow or Gold Beets",
						"Specialty Beets", "Sugar Beets", "Detroit Dark Red",
						"Cylindra Beets", "Egyptian Flat Beets",
						"Pickled Beets" },
				{ "F1 Hybrid Sweet Bok Choy", "F1 Hybrid Dwarf Bok Choy",
						"Dwarf Bok Choy", "Extra Dwarf Bok Choy",
						"Tall Bok Choy", "F1 Hybrid Taiwan Bok Choy",
						"Taiwan Bok Choy", "Huo Guo Chai",
						"F1 Hybrid Joi Choi", "Takuchoy", "Hanakan, Hybrid",
						"Mei Qing Choi, Hybrid", "Petite Star, Hybrid",
						"San Fan, Hybrid", "Shanghai", "Fun Jen, Hybrid",
						"Golden Yellow, Hybrid", "Purple Choi, Hybrid",
						"Red Choi, Hybrid", "Red Tatsoi, Hybrid",
						"Red Violet, Hybrid", "Da Cheong Chae, Hybrid",
						"Dwarf 4″, Hybrid", "Extra Dwarf Pak Choi", "Taisai",
						"Tatsoi", "Choi Sum", "Chin-Chiang" },
				{ "Italian Broccoli", "Heading Broccoli", "Broccoli Raab",
						"Romanesco Broccoli", "Sprouting Broccoli",
						"Chinese broccoli" },
				{ "Quarantina", "Spigariello Liscia", "Spigariello",
						"Hon Tsai Tai", "Sessantina", "Not specified",
						"Super Rapini", "Sorrento", "Zamboni", "Cima di Rapa",
						"White Sprouting Broccoli",
						"Early Purple Sprouting Broccoli",
						"Late Purple Sprouting Broccoli", "Rapini",
						"Early Fall", "Spring", "Cima di rape Spigarello",
						"Novantina", "Maceratese", "Summer Jean",
						"Rapa da Foglia senza Testa." },
				{ "Spring Cabbage", "Summer Cabbage", "Winter Cabbage",
						"Savoy Cabbage", "Red Cabbage", "Chinese Cabbage",
						"Oxheart Cabbage", "White Cabbage", "Napa Cabbage",
						"Brussels Sprouts", "Green Cabbage", "Bok Choy",
						"Earliana Cabbage", "Orient Express Cabbage",
						"King Slaw Cabbage", "Salad Delight Cabbage",
						"Early Flat Dutch Cabbage",
						"Early Jersey Wakefield Cabbage",
						"Golden Cross Cabbage", "Stone head Cabbage",
						"Pusa Drumhead Cabbage", "Golden Acre Cabbage",
						"September Early Cabbage", "Two Seasons Cabbage" },
				{ "Chantenay Carrot", "Miniature/Baby Carrot",
						"Imperator Carrot", "Danvers Carrot", "Orange Carrot",
						"Yellow Carrot", "Red Carrot", "White Carrot",
						"Purple Carrot", "Black Carrot", "Maroon Carrots",
						"Golden Ball Carrot", "Saint Valery Carrot",
						"Long Orange Carrot" },
				{ "Purple", "Orange", "Green cauliflower" },
				{ "Wild Celery", "Celery Stalks", "Celeriac" },
				{ "Cherry pepper", "Anaheim pepper", "Bell pepper",
						"Jalapeño pepper", "Serrano pepper", "Cayenne pepper",
						"Tabasco pepper", "Thai pepper", "Rocoto pepper",
						"Habanero chili pepper", "Ghost pepper",
						"Pepper Senorita F1", "Pepper Cajun Belle F1",
						"Pepper Mariachi F1", "Pepper Holy Mole F1",
						"Pepper Chile G76 F1", "Pepper Tiburon F1",
						"Pepper Sequoia F1", "Pepper Capulin F1",
						"Pepper Hot Portugal", "Pepper Stoked F1",
						"Pepper Hungarian Wax", "Pepper El Hombre F1",
						"Pepper Mesilla F1", "Pepper Cheyenne F1",
						"Pepper Cayenne Long Slim",
						"Pepper Cayenne Large Thick",
						"Pepper Large Red Cherry Hot", "Pepper Jalapeno M",
						"Pepper Sureno F1", "Pepper Serrano Del Sol F1",
						"Pepper Telica F1", "Pepper Suribachi F1",
						"Pepper Mucho Nacho F1", "Pepper Thai Hot",
						"Chipotle Pepper", "Habanero Pepper", "Ancho Pepper",
						"Big Jim Pepper", "Guajillo Pepper", "Mirasol Pepper",
						"Pepperoncini Pepper", "Santa Fe Grande Hot Pepper",
						"Thai Hot Ornamental Pepper", "Yummy Snacking Pepper",
						"Sweet Banana Pepper", "Sweet Red Cherry Pepper",
						"Pimiento Pepper", "Merlot Purple Pepper",
						"Habanero Hot Pepper", "Fresno Chili Hot Pepper",
						"Cowhorn Hot Pepper", "Cajun Belle Pepper",
						"Anaheim Hot Pepper", "Sangria Pepper" },
				{ "Common Chives", "Garlic Chives", "Giant Siberian Chives",
						"Allium Schoenoprasum", "Pink Chives", "Chinese Chives" },
				{ "Champion Collard Green", "Vates Collard Greens",
						"Morris Heading Collard Greens",
						"Georgia Southern Collard Greens" },
				{ "Jubilee", "Merit", "Silver Queen", "Sweet G-90",
						"Bodacious", "Calico Belle", "Incredible", "Miracle",
						"Platinum Lady", "Snowbelle", "Tendertreat" },
				{ "Armenian Cucumbers", "English Cucumbers",
						"Garden Cucumbers", "Kirby Cucumbers",
						"Lemon Cucumbers", "Persian Cucumbers" },
				{ "Dukat Dill", "Bouquet Dill", "Superdukat Dill",
						"Long Island Mammoth Dill", "Fernleaf Dill" },
				{ "Chinese Eggplant", "Indian Eggplant ",
						"& Indian Paint Eggplant", "Japanese Eggplant",
						"Pingtung Long Eggplant", "Thai Eggplant",
						"White Eggplant", "Pea Eggplant", "Sicilian Eggplant",
						"Italian Eggplant", "African Garden Eggs",
						"Chinese Round Mauve Eggplant", "Black Beauty Eggplant" },
				{ "Spring Green Peas", "Survivor Green Peas",
						"Thomas Laxton Green Peas", "Wando Green Peas",
						"Garden Sweet Green Peas", "Mr. Big Green Peas",
						"Early Perfection Green Peas", "Maestro Green Peas",
						"Lincoln Green Peas", "Little Marvel Green Peas",
						"Misty Shell Green Peas", "Snowbird Green Peas",
						"Gray Sugar Green Peas", "Sugar Daddy Green Peas",
						"Oregon Sugar Pods Green Peas",
						"Mammoth Melting Sugar", "Oregon Sugar Pod #2",
						"Avalanche Green Peas", "Sugar Bon Green Peas",
						"Sugar Snap Green Peas", "Super Snappy Green Peas",
						"Sugar Ann Green Peas",
						"Super Sugar Snap VP Green Peas" },
				{ "Jolie Endive", "Armantes Endive", "Brillantes Endive" },
				{ "Garden Sorrel" },
				{ "Porcelain Garlics", "Rocambole Garlics",
						"Purple Stripe Garlics", "Artichoke Garlics",
						"Silverskin Garlics", "The Creole Garlics",
						"Asiatic Garlics", "Turban Garlics", "Elephant Garlic" },
				{ "Curly Kale", "Lacinato Kale (Dino Kale)", "Premier Kale",
						"Redbor Kale", "Siberian Kale", "Walking Stick Kale",
						"Red Russian Kale", "Kamome Red Kale",
						"Ornamental Kale", "Winter Red Kale", "Red Ursa Kale",
						"Tuscan Kale", "Rainbow Tuscan Kale", "Scottish Kale",
						"Caledonian Kale", "Grampain Kale" },
				{ "Grand Duke", "Purple Vienna", "White Vienna" },
				{ "King Richard", "Varna", "Dawn Giant", "American Flag",
						"Albinstar Baby", "Otina" },
				{ "Iceberg Lettuce", "Butterhead - Boston",
						"Butterhead - Bibb", "Green Leaf Lettuce",
						"Red Leaf Lettuce", "Oak Leaf Lettuce",
						"Romaine Lettuce" },
				{ "Specialty Okra", "Red Burgundy Okra", "Silver Queen Okra",
						"Star of David Okra", "Alabama Red Okra",
						"Cow Horn Okra", "Hill Country Heirloom Red Okra",
						"Burmese Okra", "Jade Okra", "Emerald Okra",
						"Chinese okra", "Purple Okra", "Louisiana Short Okra" },
				{ "Snow White Hybrid Onion", "White Granex Onion",
						"Bianca Onion", "Gladalan White Onion",
						"White Spanish Onion", "Mild Onions",
						"Candy Hybrid Onion", "Walla Walla Sweet Onion",
						"Granex Yellow Hybrid Onion",
						"Texas Super sweet Onion",
						"Sweet and Early Hybrid Onion",
						"Yellow Ebenezer Onion", "Savannah Sweet Onion",
						"Sweet Spanish Hybrid Onion", "Texas Grano Onion",
						"Giant Red Hamburger Onion", "Salad Red Onion",
						"Red Delicious Onion", "Redshine Onion",
						"Redwing Onion", "Red Emperor Onion",
						"Evergreen Long White Onion", "Parade Onion",
						"White Lisbon Onion", "Creamgold Onion",
						"Murray Brown Onion", "Baby Onion", "Pearl Onion",
						"Bermuda Onion", "Egyptian Onion", "Fresh Onion",
						"Maui Onion", "Scallion onion", "Shallot onion",
						"Spanish Onion", "Sweet Onion", "Vidalia Onion",
						"Cipollini Onion", "Yellow Multiplier Onion",
						"Gurney’s Sweet Mesquite Hybrid Onion" },
				{ "Harris Model Parsnips", "All American Parsnips",
						"Hollow Crown Parsnips", "Cobham Marrow Parsnips",
						"The Student Parsnips" },
				{ "Cherry pepper", "Anaheim pepper", "Bell pepper",
						"Jalapeño pepper", "Serrano pepper", "Cayenne pepper",
						"Tabasco pepper", "Thai pepper", "Rocoto pepper",
						"Habanero chili pepper", "Ghost pepper",
						"Pepper Senorita F1", "Pepper Cajun Belle F1",
						"Pepper Mariachi F1", "Pepper Holy Mole F1",
						"Pepper Chile G76 F1", "Pepper Tiburon F1",
						"Pepper Sequoia F1", "Pepper Capulin F1",
						"Pepper Hot Portugal", "Pepper Stoked F1",
						"Pepper Hungarian Wax", "Pepper El Hombre F1",
						"Pepper Mesilla F1", "Pepper Cheyenne F1",
						"Pepper Cayenne Long Slim",
						"Pepper Cayenne Large Thick",
						"Pepper Large Red Cherry Hot", "Pepper Jalapeno M",
						"Pepper Sureno F1", "Pepper Serrano Del Sol F1",
						"Pepper Telica F1", "Pepper Suribachi F1",
						"Pepper Mucho Nacho F1", "Pepper Thai Hot",
						"Chipotle Pepper", "Habanero Pepper", "Ancho Pepper",
						"Big Jim Pepper", "Guajillo Pepper", "Mirasol Pepper",
						"Pepperoncini Pepper", "Santa Fe Grande Hot Pepper",
						"Thai Hot Ornamental Pepper", "Yummy Snacking Pepper",
						"Sweet Banana Pepper", "Sweet Red Cherry Pepper",
						"Pimiento Pepper", "Merlot Purple Pepper",
						"Habanero Hot Pepper", "Fresno Chili Hot Pepper",
						"Cowhorn Hot Pepper", "Cajun Belle Pepper",
						"Anaheim Hot Pepper", "Sangria Pepper" },
				{ "Russet Potatoes", "Red Potatoes", "White Potatoes",
						"Yellow Potatoes", "Purple/Blue Potatoes",
						"Fingerling Potatoes", "Petite Potatoes",
						"Russian Banana (waxy) Potatoes",
						"Purple Majesty (all-purpose) Potatoes",
						"Norland Red (all-purpose) Potatoes",
						"Exquisa Potatoes", "Cara Potatoes",
						"Yukon Golds Potatoes", "Red Bliss Potatoes",
						"New Potatoes", "Sweet Potatoes", "Annabelle Potatoes",
						"Anya Potatoes", "Apache Potatoes", "Bambino Potatoes",
						"Carlingford Potatoes", "Desiree Potatoes",
						"Duke of York Potatoes", "Dunbar Rover Potatoes",
						"Estima Potatoes", "Harmony Potatoes",
						"Innovator Potatoes", "Kestrel Potatoes",
						"Lady Balfour Potatoes", "Maris Piper Potatoes",
						"Melody Potatoes", "Mozart Potatoes",
						"Osprey Potatoes", "Red King Edward Potatoes",
						"Romano Potatoes", "Rooster Potatoes",
						"Roseval Potatoes", "Saxon Potatoes",
						"Shetland Black Potatoes", "Vales Sovereign Potatoes",
						"Vivaldi Potatoes", "Wilja Potatoes",
						"Yukon Gold Potatoes", "Witchill Potatoes",
						"Queen Potatoes", "Nadine Potatoes", "Coltra Potatoes" },
				{ "Aladdin Pumpkin", "American Tonda Pumpkin",
						"Amish Pie Pumpkin", "Baby Bear Pumpkin",
						"Baby Boo Pumpkin", "Baby Pam Sugar Pie Pumpkin",
						"Big Rock Pumpkin", "Big Max Pumpkin",
						"Charisma Pumpkin", "Cinderella Pumpkin",
						"Cotton Candy Pumpkin",
						"Cushaw Green and Gold Pumpkin", "Fairytale Pumpkin",
						"Full Moon Pumpkin", "Halloween in Paris Pumpkin",
						"Hooligan Pumpkin", "Howden Pumpkin",
						"Howden Biggie Pumpkin", "Jack-be-Little Pumpkin",
						"Jack-be-Quick Pumpkin", "Kakai Pumpkin",
						"La Estrella Pumpkin", "Lil’ Pumpkemon Pumpkin",
						"Long Island Cheese Pumpkin", "Lumina Pumpkin",
						"Mandy Pumpkin", "Marina Di Chioggia Pumpkin",
						"Neon Pumpkin", "New England Pie Pumpkin",
						"Old Zebs Pumpkin", "One Too Many Pumpkin",
						"Orange Smoothie Pumpkin", "Pic-A- Pie Pumpkin",
						"Prizewinner Pumpkin", "Queensland Blue Pumpkin",
						"Red Warty Thing Pumpkin", "Rock Star Pumpkin",
						"Snack Jack Pumpkin", "Valenciano Pumpkin",
						"Wolf Pumpkin", "Munchkin Pumpkin",
						"Magic Lantern F1 Pumpkin", "Merlin F1 Pumpkin",
						"White Ghost Pumpkin", "Lakota Pumpkin",
						"Kabocha Pumpkin", "Blue Lakota Pumpkin",
						"Zucca Rotondo Pumpkin", "Atlantic Giant Pumpkin",
						"Connecticut Field Pumpkin", "Lil’ Goblin Pumpkin",
						"Sugar Pumpkin", "Casper Pumpkin",
						"Golden nugget Pumpkin", "Silver Moon Pumpkin" },
				{ "Chioggia", "Treviso", "Tardivo", "Leonardo", "Milan",
						"Ambra" },
				{ "Black radish", "Daikon Radish", "Watermelon Radish",
						"Horseradish", "Cherry Belle Radish",
						"Black Spanish Round Radish", "Crimson Giant Radish",
						"Perfecto Radish", "French Breakfast Radish",
						"Red Globe Radish", "White Icicles Radish",
						"California Mammoth White Radish", "Champion Radish",
						"Easter Egg Radish", "Plum Purple Radish",
						"Red King Radish", "Roodbol Radish",
						"Sicily Giant Radish", "Snow Belle Radish",
						"Bunny Tail Radish", "Burpee White Radish",
						"Early Scarlet Globe Radish", "China Rose Radish",
						"Chinese White Radish", "Sparkler Radish",
						"Cherriette Radish", "D’Avignon’ Radish",
						"Nero tondo Radish", "Beauty Heart Radish" },
				{ "Timperley Early", "Victoria", "Glaskins Perpetual" },
				{ "American Purple Top Rutabaga", "Joan Rutabaga",
						"Laurentian Rutabaga", "Marian Rutabaga",
						"Heirloom and Gourmet Rutabaga" },

				{ "Savoy spinach", "Flat-leaf spinach", "Semi-savoy spinach",
						"Smooth-Leafed Spinach", "New Zealand Spinach",
						"Malabar Spinach" },
				{ "Atlas butternut squash", "Avalon butternut squash",
						"Butternut 401 squash", "Waltham Butternut",
						"Argonaut butternut squash", "Ultra butternut squash",
						"Quantum butternut squash", "Butter Boy Hybrid",
						"Burpee’s Butterbush", "Autumn Glow butternut squash" },
				{ "Beauregard Sweet Potatoes", "Allgold Sweet Potatoes",
						"Apache Sweet Potatoes",
						"Bunch Porto Rico Sweet Potatoes",
						"Centennial Sweet Potatoes", "Cherokee Sweet Potatoes",
						"Amish Red Sweet Potatoes",
						"Continental Red Sweet Potatoes",
						"Carolina Ruby Sweet Potatoes",
						"Dianne Sweet Potatoes", "Garnet Sweet Potatoes",
						"Georgia Jet Sweet Potatoes",
						"Cordner’s Red Sweet Potatoes",
						"Star Leaf Sweet Potatoes",
						"White Delite Sweet Potatoes",
						"Nancy Hall Sweet Potatoes", "Sumor Sweet Potatoes",
						"Picadita Sweet Potatoes" },
				{ "Pear Tomato", "Branch Tomato", "Raf Tomato",
						"Cherry Tomato", "Globe Tomato", "Roma Tomato",
						"Sun Gold Tomato", "Big Beef Tomato", "Juliet Tomato",
						"Beefsteak Tomato", "Eva Purple Ball Tomato",
						"Cherokee Purple Tomato", "Green Zebra Tomato",
						"Black Krim Tomato", "Japanese Tomato",
						"Oxacan Jewel Tomato", "Black Pear Tomato",
						"Mexican (Red Calabash) Tomato",
						"Yellow Valencia Tomato", "Black Russian Tomato",
						"Brandy Wine Tomato", "Hillbilly Tomato",
						"German Stripe Tomato", "Polish Linguisa Tomato",
						"Mortgage Lifter Tomato",
						"Ramapo Jersey Heirloom Tomato",
						"Powers Heirloom Tomato", "Purple Russian Tomato",
						"Pink Ping Pong Tomato", "Sunray Tomato",
						"Early Girl Tomato", "Mama Leone Italian Tomato",
						"Tye-Dye Tomato", "Ananas Noire Tomato",
						"Russian Tomato", "Roman Candles Tomato",
						"Big Pink Tomato", "Quick Pick Tomato",
						"Rutger Tomato", "San Marzano Tomato",
						"Moneymaker Tomato", "Bradley Tomato",
						"Park’s Whopper Tomato", "Marglobe Supreme Tomato",
						"Amai Tomato", "Amana Orange Tomato",
						"Amarillo Yellow’ Tomato", "Amelia Tomato",
						"Amish Paste Tomato", "Andrina Tomato",
						"Angelo’s Red Tomato", "Anna Russian Tomato",
						"Arbuznyi Tomato", "Armenian Tomato",
						"Ashleigh Tomato", "Tomato Anna Aasa",
						"Applause Tomato", "Arkansas Traveler Tomato",
						"Aunt Gertie’s Gold Tomato", "Aunt Ginny’s Tomato",
						"Austin’s Red Pear Tomato", "Azoychaka Tomato",
						"Baby Cakes Tomato", "Banana Legs tomato",
						"Basket Vee Tomato", "Beam’s Yellow Pear Tomato",
						"Beef master Tomato", "Bella Rosa Tomato",
						"Bellestar Tomato", "Better Boy tomato",
						"Bi-Color Cherry Tomato", "Big Boy Tomato",
						"Big Rainbow Tomato", "Big Raspberry Tomato",
						"Big Zebra Tomato", "Black Cherry tomato",
						"Black Pearl tomato", "Black Prince Tomato",
						"Black Sea Man Tomato", "Black Velvet Tomato",
						"Blush Tomato", "Box Car Willie Tomato",
						"Brandy master Pink Tomato", "Brandywine Black Tomato",
						"Cabernet tomato", "Cacady’s Folly Tomato",
						"Capaya Tomato", "Carbon Tomato", "Carmelita Tomato",
						"Carmello Tomato", "Ceylon Tomato", "Charger Tomato",
						"Chello Tomato", "Cherokee Chocolate Tomato",
						"Christmas Grapes Tomato", "Conestoga Tomato",
						"Copia Tomato", "Crista Tomato", "Dafel Tomato",
						"Debaro Tomato", "Earliana Tomato",
						"Elberta Girl Tomato", "Elfin Tomato", "Empire Tomato",
						"Enchantment Tomato", "Fantastic Tomato",
						"Ferline Tomato", "Floradade Tomato",
						"Floralina Tomato", "Frazier’s gem Tomato",
						"Gabrielle Tomato", "Galina Tomato",
						"Gardener’s Delight tomato", "Georgia Streak Tomato",
						"German Giant Tomato", "German Head tomato",
						"German Pink Tomato", "Giant Syrian tomato",
						"Golden Gem tomato", "Ildi Tomato",
						"Isis Candy tomato", "Maglia Rosa Tomato",
						"Manitoba Tomato", "Margo Tomato", "Momotaro Tomato",
						"Red Rose Tomato", "Zapotec Pink Ribbed tomato" },

				{ "Purple Top Milan Turnip", "Manchester Market Turnip",
						"Tokyo Turnip", "Golden Ball Turnip",
						"Snow Ball Turnip", "Green Globe Turnip",
						"All White Turnips", "Baby Turnips",
						"Brassica rapa Turnip", "Amber Globe Turnip",
						"White Egg Turnip" },
				{ "Green Cardamom", "Brown Cardamom", "Ground Cardamom" },
				{ "Leaf Cilantro", "Seed Coriander", "Vietnamese Cilantro",
						"Culantro" },
				{ "Baby Ginger", "Jamaican Ginger", "Organic Ginger",
						"Thai Ginger", "Yellow Ginger" },
				{ "Cinnamon" },
				{ "Africa", "Asia", "Americas", "Manila Tamarind" },
				{ "Peppermint", "Spearmint", "Chocolate Mint",
						"Fruit-flavored mint", "Corsican Mint", "Bowles Mint",
						"Catnip, or Catmint", "Bergamot, or Lemon Mint",
						"Lemon Balm, or Melissa Mint", "Apple Mint",
						"Pineapple Mint", "Ginger Mint", "Curly Spearmint",
						"Water Mint", "Corn Mint", "Pennyroyal Mint",
						"Asian Mint", "Horse Mint" },
				{ "Sargol Saffron", "Iranian Saffron", "Mancha Saffron",
						"Poushal Safforn", "Bunched Saffron", "White Saffron",
						"Konch Saffron", "Kashmiri Saffron", "Persian Saffron",
						"Moroccan Saffron", "Spanish Saffron",
						"Negin sargol saffron", "Dasteh Saffron" } };
		String[][] Health_Benefits = {
				{ "High in Antioxidants", "Cancer Prevention",
						"Increased Bile Flow", "Liver protection",
						"Digestive Health", "Hangover Treatment",
						"Lower Cholesterol", "High in Fiber", "Diabetes",
						"Hair Health", "Relieves Dyspepsia Symptoms" },
				{ "Cancer Prevention", "High in Antioxidants",
						"High in Vitamin C", "High in Vitamin A",
						"High in Vitamin K", "Mineral Rich", "Low in Oxalate",
						"Bone Health", "Weight Loss",
						"Reduce chronic inflammation",
						"Protect the aging brain\nand cognitive decline",
						"Healthy immune system", "Prenatal health",
						"Metabolic functions", "Eyesight", "Great aphrodisiac",
						"Heart Health Benefits" },
				{ " Like a detox", "For anti-aging purposes",
						"As an aphrodisiac", "Cancer Prevention",
						"Good for Heart health", "Preventing birth defects",
						"Antioxidants", "Cancer", "Better Sex ",
						"& Reproductive System Health", "Bone Health",
						"Depression", "Supports digestion",
						"Reduce Hypertension", "Diabetes", "Help weight loss",
						"Good during pregnancy", "Help with a hangover",
						"Strengthen the brain", "Increase milk production",
						"Help balance out your electrolytes",
						"Promotes healthy skin" },
				{ "Promotes heart health", "Skin and Hair Health",
						"Prevents some cancers", "Boosts the immune system",
						"Provides antibacterial protection",
						"Basil helps blood clot properly",
						"Preserves DNA Integrity", "Kills Bacteria",
						"Reduces Arthritis Pain", "Bone and Connective Tissue",
						"Digestive Tract Health", "Healing Power",
						"Prevents Common Cold", "Enhances Memory",
						"Relieves Cough", "Stress Buster", "Prevents Acne",
						"Enhances Oral Health", "Eliminates Kidney Stones",
						"Relieves Headache", "Antimicrobial Properties",
						"Anti-inflammatory Properties",
						"Chronic Disease Prevention", "Treats Ear Infections",
						"Blocks UV Rays", "Promotes Clear Vision",
						"For sore throat", "Indigestion",
						"Reduce your cholesterol levels",
						"Reduce unwanted inflammation",
						"Prevent or destroy yeast infections" },
				{ "Heart-Helpers", "Low In Fat", "Pack Protein",
						"Balance Blood Sugar", "Cut Cancer Risk",
						"Will Move You", "Satisfy You", "Convenient",
						"Wallet-Friendly", "Nutrient-Rich", "Versatile" },
				{ "Weight Loss", "Brain and Energy Boost", "Nature’s Viagra",
						"Anti-Inflammatory Benefits", "Fight Cancer Cells",
						"Cell Detoxification", "and Cleansing",
						"Improved Mental Health", "Good for heart",
						"Prevents Birth Defects",
						"Prevent respiratory problems",
						"Instant Energy Source", "Capillary fragility",
						"Prevents Osteoporosis", "Macular degeneration",
						"Prevents Cognitive Disorders", "Good for liver",
						"Prevent Strokes\n& Heart Attacks",
						"Reduce Blood Pressure", "Lower Cholesterol Levels",
						"Prevents Colon Cancer", "Mind-calming Effect" },
				{ "Cancer Prevention", "Digestive Health", "Eye Health",
						"Blood Pressure", "Weight Loss", "Pregnancy Health",
						"Immune Support", "Strong Bones", "Blood and Nerves",
						"Antioxidant Protection", "Cardiovascular Health!",
						"Rich in Vitamin C", "Rich in Potassium" },
				{ "Cancer prevention", "Cholesterol reduction",
						"Powerful antioxidant", "Bone health", "Heart health",
						"Diet aid" },
				{ "Increased Immune Function", "Reduced Cancer Risk",
						"Reduced Risk of Colon Cancer",
						"Protection Against Heart Disease",
						"Slowing the progression of AIDS", "Slowing Aging",
						"DNA Repair and Protection",
						"Protection Against Dementia",
						"Alleviation of Hypertension", "Promoted Eye Health",
						"Alzheimer's Protection", "Osteoporosis Protection",
						"Stroke Prevention",
						"Reduced Risk of Type II Diabetes",
						"Antioxidant Protection",
						"Prevention of Epileptic Seizures",
						"Alleviation of the Common Cold",
						"Prevention of Alopecia", "Alleviation of Inflammation" },
				{ "Prevents Cancer", "Treat peptic ulcers",
						"Anti-inflammatory properties", "Boosts immune system",
						"Prevent cataract risk", "Cabbage for Weight Loss",
						"Relieve constipation", "Avoid Skin Disorders",
						"Relieve muscle soreness", "Mastitis",
						"Decrease Cholesterol level", "Diabetics",
						"During Pregnancy", "Heart Disease", "Cures Obesity",
						"Maintaining process of gastric", "Boost energy",
						"Relieve muscle soreness", "Slow aging",
						"Lower serum cholesterol" },
				{ "Improved Vision", "Cancer Prevention", "Anti-Aging",
						"Nourish Skin", "A Powerful Antiseptic",
						"Beautiful Skin (from the outside)",
						"Prevent Heart Disease", "Cleanse the Body",
						"Healthy Teeth and Gums", "Prevent Stroke",
						"Macular Degeneration", "Antioxidants", "Diabetes",
						"Prevention of Digestive Disorders",
						"Prevention of Infections", "Treatment of Worms",
						"Help Lower Cholesterol", "Enlarged Prostate",
						"Diarrhea" },
				{ "Fight Cancer", "Boost Heart Health",
						"It's Anti-Inflammatory",
						"It's Rich in Vitamins and Minerals",
						"Boost Your Brain Health", "Detoxification Support",
						"Digestive Benefits", "Antioxidants",
						" & Phytonutrients Galore" },
				{ "Prevents Cancer", "Cholesterol", "Digestion",
						"Blood Pressure and Diuretic Uses",
						"Anti-Inflammatory", "Insomnia", "Weight loss",
						"Urinary Stones", "Constipation", "Cooling",
						"Kidney function", "Brain health",
						"Repel mosquitoes naturally",
						"Boost your man’s fertility", "Fungal infections",
						"Gout", "Celery and pain relief", "Good antiseptic",
						"Bad breath" },
				{ "Headache help", "Arthritis relief", "Sinus soother",
						"Anti-inflammatory", "Gastric relief", "Fight Cancer",
						"Provide Pain Relief", "Soothe Intestinal Diseases",
						"Burn Fat and Lose Weight", "Protect Your Heart",
						"Repel Insects", "Protect Skin",
						"Contain Vitamins and Minerals",
						"Contain Antioxidants", "Relief from Indigestion" },
				{ "Antibiotic", "Anti-Inflammatory", "Anti-Carcinogenic",
						"Circulatory", "Cardiovascular", "Allicin",
						"Digestion", "Bone Strength", "Antioxidants",
						"Low in Calories, Fat and Salt" },
				{ "Detox Benefits", "Broad Antioxidant Protection",
						"Anti-inflammatory Benefits", "Reduces Cancer Risk",
						"Enhances the Body Systems", "Benefits Digestion",
						"Optimizing Immune Function", "Promote Lung Health",
						"Cardiovascular Protection" },
				{ "Good for Digestion", "Prevents Anemia", "Increased Energy",
						"Lowers LDL Cholesterol", "Facilitates Weight Gain",
						"Prevents Diabetes", " & Hypertension",
						"Stronger Connective Tissue", "Improves Vision",
						"Anti-cancer Properties",
						"Beneficial during Pregnancy", "Beneficial for Heart",
						"Prevents Alzheimer’s disease" },
				{ "Protect Your Brain", "Reduce Your Risk of Cancer",
						"Fight Inflammation", "Antioxidant Properties",
						"Freshen Your Breath", "Manage Stress",
						"Support Your Digestive Health",
						"Maintain a Healthy Weight", "Support Heart Health" },
				{ "Bone Health", "Anti-Bacterial", "Free Radical Protection",
						"Digestive Benefits", "Hiccup Treatment",
						"Headache Help", "Calming Effect", "Digestion",
						"Insomnia", "Diarrhea", "Dysentery",
						"Menstrual Disorders", "Respiratory Disorders",
						"Oral Care", "Cancer", "Heartburn",
						"Bone/Teeth Enhancements", "Cold/Flu Remedies",
						"Bad Breath" },
				{ "Reduced Risk of Cancer", "Weight Loss", "Better Skin Tone",
						"Type 2 Diabetes Management",
						"Aubergines as an Antibacterial", "Cholesterol",
						"Eating Eggplant for the Heart",
						"Keeping the Mind Healthy",
						"Eggplant for Healthy Digestion",
						"Normalizing Iron Levels in the Body",
						"Keeping Hair, Skin ", "& Nails Healthy with Eggplant",
						"Quitting Smoking", "Constipation", "Insomnia",
						"Controls iron levels in the body", "Bone Health" },
				{ "Weight Management", "Healthy bones",
						"Reduces bad cholesterol",
						"Prevents from stomach Cancer",
						"Promote cardiovascular health",
						"Improve your immune system",
						"Keep your digestive system healthy",
						"Improve your metabolism", "Healthy skin and hair" },
				{ "Cures acne", "Asthma", "Anemia", "Cancer prevention",
						"Constipation", "Treats eye complications",
						"Liver and gall bladder", "Helps weight loss",
						"Vitamins", "Appetite stimulant",
						"Alzheimer’s disease", "Healthy bones and teeth",
						"Digestive health", "Heart health", "Pregnancy" },
				{ "Digestive Health", "Blood Pressure", "Cancer Prevention",
						"Eyesight Improvement", "Circulation and Energy",
						"Immune System Health", "Skin Conditions",
						"Heart Health and Diabetes", "Kidney Health" },
				{ "Garlic Reduces Cholesterol", "Garlic is an Antioxidant",
						"Garlic is an Antibiotic", "Cardiovascular health",
						"Toothaches", "Allergies", "Diabetes", "Hypertension",
						"Colds", "Cancer", "Impotence", "Pregnancy",
						"Anti-Bacterial", "Digestive System Disorders",
						"Increase immunity", "Assist with weight loss",
						"Anti-inflammatory Health", "Prevents Atherosclerosis",
						"Improves Iron metabolism",
						"Removes poison from Insect Bites",
						"Protect against Metal poisoning", "Relief for Herpes",
						"Relieves Sinusitis", "Reduces Snoring",
						"Prevents Cataracts", "Prevents Tuberculosis",
						"Effective for Food poisoning" },
				{ "Anti-inflammatory", "Cancer Prevention",
						"Lowers Cholesterol", "Prevents Bone Loss",
						"Reduces Macular Degeneration", "Great For eyes",
						"Great For your heart",
						"Detoxification and Weight loss",
						"Strengthen your Immune System", "Fighting Disease",
						"Blood health", "Helpful during pregnancy",
						"Prevents breast cancer", "Get healthy hair",
						"Improves Sleep", "Combats Illness",
						"Eliminate Rheumatoid Arthritis",
						"Promotes Urinary Health", "Digestion Aid" },
				{ "Kohlrabi is Nutrient Dense",
						"Good for the Circulatory System",
						"Maintains Healthy Immune System",
						"Promotes Healthy Digestion",
						"Assists in Proper Muscle ", "& Nerve Functions",
						"Cancer Prevention", "Weight Loss", "Acidosis",
						"Asthma", "Heart problems", "Indigestion",
						"Muscle and nerve functions", "Skin Problems",
						"Stabilize blood pressure" },
				{ "Anemia", "Anti-inflammatory and anti-septic", "Aphrodisiac",
						"Balsamic action", "Leek for digestion",
						"High blood pressure", "High cholesterol",
						"Nervous system", "Purifying action",
						"Strengthen Bone", "Leek for cancer",
						"Leek for anti-oxidants", "Leek for pregnant women",
						"Leek for insect bites", "Immune function",
						"Cardio vascular support", "Antibacterial Properties" },
				{ "Helps Weight Loss", "Heart Healthy", "Omega-3 Fatty acids.",
						"Complete Protein", "Helps with Insomnia",
						"Lettuce is Alkaline Forming", "Low Glycemic Index",
						"Whole Life Food", "Lettuce Tastes Great." },
				{ "Okra Promotes a Healthy Pregnancy",
						"Helps Prevent Diabetes", "Helps with Kidney Disease",
						"Supports Colon Health",
						"Could Help with Respiratory Issues", "like Asthma",
						"Promotes Healthy Skin", "Prevents Anemia",
						"Aids Weight Loss", "Improves Heart Health",
						"Improves Hair Problems", "Improves Immunity",
						"Improves Good Eyesight", "Developing stomach ulcers",
						"Cure for dysentery and diarrhea",
						"Increases blood count",
						"Controls the Body’s Cholesterol Level",
						"Relieves Constipation ", "& Other Stomach Problems" },
				{ "Cardiovascular Help", "Cancer Prevention",
						"Anti-Bacterial Properties", "Protects Your Brain",
						"Strengthens Bones", "Aids Digestion",
						"Good Oral Health", "Relieving Earache",
						"Insect repellent", "Purify blood",
						"Improve Sexual Power", "Osteoporosis",
						"Improve the quality of your hair", "Asthma",
						"Diabetes", "Sinus Infections", "Insomnia",
						"Protective Use", "Boosting immunity of the body",
						"Anti-septic nature", "Cough treatment",
						"Good blood thinners",
						"Strengthening Teeth Structural",
						"Low Sugar, Almost Fat Free", "In Jaundice", "Piles",
						"Arthritis", "Skin Care" },
				{ "Help regulate the immune response",
						"Reduce the risk of type 2 diabetes",
						"Anti-Cancer Components",
						"Supports Healthy Blood Pressure",
						"Helps Prevent Nutrient Deficiencies",
						"Source of Dietary Fiber",
						"Fortified bones and Strong Teeth!",
						"Excellent for Your digestive system!",
						"Cardiovascular Health", "Prevents from blood loss",
						"Prevents aging of skin", "Strengthens muscles",
						"Benefit asthma patients", "Benefit pregnant women" },
				{ "Headache help", "Arthritis relief", "Sinus soother",
						"Anti-inflammatory", "Gastric relief", "Fight Cancer",
						"Provide Pain Relief", "Soothe Intestinal Diseases",
						"Burn Fat and Lose Weight", "Protect Your Heart",
						"Repel Insects", "Protect Skin",
						"Contain Vitamins and Minerals",
						"Contain Antioxidants", "Relief from Indigestion" },
				{ "Reduce inflammation", "Prevent cardiovascular disease",
						"Weight Gain", "Digestion", "Skin Care", "Scurvy",
						"Rheumatism", "High Blood Pressure", "Brain Function",
						"Heart Diseases", "Kidney Stones", "Diarrhea",
						"Weight Loss", "Anticancer Properties",
						"Vitamin Booster", "Gut", "Stress",
						"Good for diabetes", "Overcoming bruises",
						"Rich in fiber", "Make the human body stronger" },
				{ "Reduce cancer risk", "Anti-Inflammatory Effect",
						"Great on your skin", "Prevents Kidney Stones",
						"Depression", "Treatment of Parasites", "Diuretics",
						"Pumpkins keep eyesight sharp",
						"Pumpkins aid weight loss",
						"Pumpkins protect the skin",
						"Pumpkin seeds can boost your mood",
						"Boost your immune system", "Regulates Cholesterol",
						"Boon For Diabetics", "Prevents premature aging",
						"Reduce the risk of hypertension",
						"Prevent constipation", "Strengthen Bones",
						"For healthy skin" },
				{ "Anti-oxidant and energy Boost", "Battling Free Radicals",
						"Weight Loss", "Rich in Minerals and Vitamins",
						"Blood Sugar Regulation", "Bile Production",
						"High blood pressure regulation" },
				{ "Fight Cancer", "Healthy Heart",
						"Digestion & Detoxification", "Weight Loss",
						"Kidney Disorders", "Blood Pressure",
						"Blood Sugar Control", "Jaundice", "Piles",
						"Urinary Disorders", "Leucoderma", "Skin Disorders",
						"Insect Bites", "Reduce Fever",
						"Adds fiber to your diet", "Great for the liver",
						"Inflammation and Detoxification" },
				{ "Weight Loss", "Cardiovascular Diseases", "Digestion",
						"Alzheimer’s Disease", "Bone Health",
						"Cancer Prevention", "Blood Circulation" },
				{ "Cancer Prevention", "High in Antioxidants",
						"Digestive Health", "High in Fiber",
						"High in Potassium", "Weight Loss", "High in Zinc",
						"Asthma", "Constipation",
						"Lower the risk of heart stroke" },

				{ "Improves Cardiovascular Health", "Cancer", "Eyesight",
						"Anti-Cancer ", "& Anti-Inflammatory Antioxidants",
						"Alleviates Fatigue", "Maintains blood Pressure",
						"Strengthens muscles", "Fetus development",
						"Anti-ulcerative", "Skin in Natural Way",
						"Protein source for infant’s growth",
						"Remain Thin and Energetic",
						"Keep Brain Active and Working",
						"Maintains your Bone Health",
						"Increases Your Muscle Strength",
						"Liver protection activity", "Kills intestinal worms",
						"Natural laxative", "Cures urinary disorders",
						"Remedy for gastric disorders",
						"Helps to build your blood",
						"Alleviates Arthritis Pain", "Preventing Diabetes",
						"Prevent Anemia", "Treat Gums Bleeding" },
				{ "Eye Health", "Weight Loss", "Blood Pressure", "Carotenoids",
						"Antioxidants", "Weight Management", "Heart Benefits",
						"Strong Bones!", "Happier Mood", "Prevent Colds",
						"Potassium and Calcium", "Good for pregnant women",
						"Fights against premature aging" },
				{ "Heart-healthy", "Rich in beta-carotene",
						"Anti-Inflammatory Properties", "Arthritis",
						"Blood Sugar Regulation", "Stomach Ulcers",
						"Emphysema", "Digestive Tract", "Immunity", "Asthma",
						"Bronchitis", "Water Balance", "Weight Gain",
						"Prevent Heart Attacks", "Stress Relief",
						"Disease Prevention", "Muscle Cramps",
						"Fetal Development", "Cancer", "Eye Health",
						"Weight loss", "Keeping Blood Pressure",
						"Keeps teeth and gums healthy",
						"Make bones strong and healthy",
						"Helps reduce cholesterol levels" },
				{ "Ward off Cancer", "Prevent DNA Damage",
						"Protect Against Thrombosis", "Ward off Inflammation",
						"Promote a healthy and rosy skin", "Boost bone health",
						"Help reduce migraines", "Boost immunity",
						"Provide natural sunscreen", "Anti-inflammatory",
						"Counteract acidosis", "Chronic Pain", "Lose Weight",
						"Lower cholesterol", "Protect against liver disease",
						"Protects against infection", "Anti-oxidant",
						"Improve gut health" },
				{ "Cancer Prevention", "Cardiovascular Health Benefits",
						"High In Antioxidants", "Bone Health", "High in Fiber",
						"Weight Loss", "Healthy Eyes", "Prevents Body Odor",
						"Good for Your Immune System", "Good For Your Blood" },
				{ "Anti-Carcinogenic Properties", "Control of Cholesterol",
						"Anti-Depressant", "Treating Urinary Disorders",
						"Cardamom for Cold and Flu",
						"Antimicrobial Properties",
						"Anti-Spasmodic Properties", "Dental Diseases",
						"Anti-Asthmatic Property",
						"Anti-Inflammatory Properties", "Detoxification",
						"Improved Blood Circulation",
						"Good for Nausea and Vomiting", "Sore Throat",
						"Hiccups", "Breath Freshener", "Improves digestion",
						"Fights anaemia", "Improves your sex life",
						"Regularizes Heart Rate", "Genito-urinary disorders",
						"Impotency" },
				{ "Digestive System", "Eye care", "Heavy Metal Detox",
						"Sedative", "Anti-allergy",
						"Anti-microbial and anti-fungal",
						"Prevention of Cancer", "Analgesic",
						"Skin inflammation", "High cholesterol levels",
						"Overcoming Diarrhea", "Mouth ulcers", "Anemia",
						"Small pox", "Menstrual disorders", "Eye care",
						"Beneficial for Skin", "Blood sugar",
						"Liver protection", "Anthelmintic properties" },
				{ "Cancer", "Nonalcoholic Fatty Liver Disease",
						"Menstrual Pain", "Nausea and Motion Sickness",
						"Bacterial Diarrhea", "Migraine Relief",
						"Respiratory problems", "Remedy for loss of appetite",
						"Toothache", "Pregnancy­Related Nausea ", "& Vomiting",
						"Promotes Healthy Heart", "Preventing travel sickness",
						" Anti­Allergy", "Bone Health", "Sexual Activity",
						"Alzheimer’s Disease" },
				{ "Lowers blood sugar levels", "Reduces Bad Cholesterol",
						"Cancer Fighter", "Antimicrobial", "Anti­Fungal",
						"Food Poisoning", "Nutrition", "Odor Neutralizer",
						" Alertness, Mood, and Memory", "Antioxidant",
						"Weight Control", " Tooth and Gum Health",
						"Insect Repellant", "Food Preservative", "Arthritis",
						"PMS and Infertility",
						"Supports healthy blood clotting",
						"Fights bacteria and fungus", "Boosts memory",
						"& protects the brain", "Brain Function",
						"Blood circulation", "Pain Relief", "Infections",
						"Protects Against Heart Disease", "Indigestion",
						"Birth control", "Breastfeeding",
						"Improves Colon Functioning", "Throat soother",
						"Improves Metabolism", "Antibacterial Properties",
						"Anti­Inflammatory", "Helps Balance Hormones",
						"Clears the Digestive Tract", "Increases Circulation",
						"Improves Your Mood", "Alzheimer’s Prevention",
						"Helps regulate menstrual cycles", "ToothAche" },
				{ "Encourages Digestive Health", "Improved Blood Sugar ",
						"& Appetite Control", "Improved Eye Health",
						"Controlled Heart Rate ", "& Blood Pressure",
						"Works as Pain Killer", "Thirst Quencher",
						"Reduces fever", "Anti­inflammatory effects",
						"Laxative", "Reduces high cholesterol",
						"Ulcers and Jaundice", "Cancer", "Conjunctivitis",
						"Good for Ears", "For a Healthy Skin" },
				{ "Allergies", "Respiratory Disorders and Coughs", "Digestion",
						" Irritable bowel syndrome (IBS)", "Nausea & Headache",
						"Asthma", "Breast Feeding", "Depression and Fatigue",
						"Skin Care and Pimples", "Memory Loss", "Weight Loss",
						"Female Sterility", "Oral Care",
						"Allergies and Hay Fever", "Helps fight cancer",
						"Helps fight oral infections",

						"Boosts immunity", "Lower Blood Pressure",
						"Relieve Pain" },
				{ "Appetite Suppressant", "Anti­Depressant Properties",
						"Supports Eyesight", "Improves Memory",
						"Treats Cancer", "Improved Mental Functioning",
						"Saffron During Pregnancy", "Asthma",
						"Arteriosclerosis", "Menstrual Relief",
						"Gas and acidity", "Athritis", "Insomnia", "Fever",
						"Digestion", "Protects Heart", "Brain health",
						"Weight loss", "Saffron for Aches and Pains",
						"Blood cell production", "Cell formation and repair",
						"Eye problem", "Maintains Bad Cholesterol",
						"Combats Weakness ", "& Promotes Strength",
						"Helps Reducing Salt Consumption",
						"Fights Respiratory Illness" } };
		String[] title = { "Nutrition Facts", "Varieties", " Health Benefits" };

		for (int i = 0; i < Vegetables.images.length; i++) {
			StaticLists.baseVegetablesArrayList.add(new BaseFruits(
					Vegetables.images[i], title, NutritionFacts1[i],
					NutritionFacts2[i], vari[i], Health_Benefits[i]));
		}

	}

}
